[package]
name = "orelang-but-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.3"
ropey = "1.6.1"
tokio = { version = "1.33.0", features = ["full"] }
tower-lsp = "0.20.0"
